### ISSUE TITLE
custom --prefix not reflected in ~/.autojump/etc/profile.d/autojump.sh

### ISSUE THREAD

**Issue by nhoffman** [joelthelion/autojump#345]
After installation like this

```
./install.py --prefix ~/local
```

the corresponding path isn't reflected in ~/.autojump/etc/profile.d/autojump.sh, with the result that the shell-specific environment files are not sourced. That is, it seems like

```
# check global install
elif [ -s /usr/local/share/autojump/autojump.${shell} ]; then
        source /usr/local/share/autojump/autojump.${shell}

fi
```

should instead be

```
# check global install
elif [ -s ~/local/share/autojump/autojump.${shell} ]; then
        source ~/local/share/autojump/autojump.${shell}

fi
```

to reflect the value of --prefix provided to the install script.

Thanks!
Noah

**Comment by wting** [comment]
Thanks for the detailed bug report. It should work in the latest version, but if not please comment here and I'll reopen.
